name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: true

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Qt and other dependencies
        uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # v1.6.3
        with:
          packages: libegl1 libopengl0 libxkbcommon0 atool
          version: 1.0

      - name: Install Hatch
        run: pip install hatch

      - name: install cwebp
        run: bash ./scripts/libwebp-dl.sh
        shell: bash

      - name: Run tests
        run: hatch test -v
