name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"
          cache: pip

      - name: Install Qt and other dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libegl1 libopengl0 libxkbcommon0 atool
          version: 1.0

      - name: Install Hatch
        run: pip install hatch "virtualenv<20.30"

      - name: install cwebp
        run: bash ./scripts/libwebp-dl.sh
        shell: bash

      - name: Run tests
        run: hatch run dev:test
